apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: admin-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: DB_DSN
              value: "root:root@tcp(mysql:3306)/ecommerce?parseTime=true"
            - name: JWT_SECRET
              value: "supersecret"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP
